spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Sanjay@987321
    url: jdbc:mysql://localhost:3306/crudmethods
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
